# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PrepApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_22db1a44a4e94db08f9c93fd8ecf49cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0486c006db264b158c77ff19cbaf7076 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_22db1a44a4e94db08f9c93fd8ecf49cf }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PrepApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_28c8424055034dffb38dc03601a35d5a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_22db1a44a4e94db08f9c93fd8ecf49cf }}/appsvc/staticsite:${{ github.sha }}'